site_name: RuTS
site_description: "Библиотека для извлечения статистик из текстов на русском языке"
repo_url: https://github.com/SergeyShk/ruTS

nav:
    - Главная:
      - О проекте: index.md
      - Установка: installation.md
      - Авторы: authors.md
    - Извлечение объектов:
      - Извлечение предложений: extractors/sentences.md
      - Извлечение слов: extractors/words.md
    - Подсчет статистик:
        - Базовые статистики: stats/basic_stats.md
        - Метрики удобочитаемости:
          - Модуль вычисления метрик: stats/readability_stats.md
          - Функции вычисления метрик: stats/readability_stats_funcs.md
        - Метрики лексического разнообразия: stats/diversity_stats.md
        - Морфологические статистики: stats/morph_stats.md        
    - Наборы данных:
        - Советские христоматии (литература): datasets/sovchlit.md
    - Визуализации:
        - Закон Ципфа: visualizers/zipf.md
        - Литературная дактилоскопия: visualizers/fingerprinting.md
    - Компоненты:
        - Компоненты: components.md  

theme:
  name: material
  language: ru
  palette:
    primary: blue
    accent: blue
  font:
    text: Source Sans Pro
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search:
      lang: 
        - ru
        - en

extra: 
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/SergeyShk
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/shk_sergey
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/kouki91/

extra_css:
  - css/mermaid.css
  - css/extra.css

extra_javascript:
  - js/config.js
  - js/mermaid.min.js
  - js/polyfill.min.js
  - js/tex-mml-chtml.js  

markdown_extensions:
  - toc:
      permalink: True
  - attr_list
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:
      generic: True